export const SPUR_COLORS: { color: string; name: string }[] = [
  { color: "#ef4444", name: "Red"        },
  { color: "#f97316", name: "Orange"     },
  { color: "#f59e0b", name: "Amber"      },
  { color: "#f29106", name: "Spur Gold"  },
  { color: "#eab308", name: "Yellow"     },
  { color: "#84cc16", name: "Lime"       },
  { color: "#22c55e", name: "Green"      },
  { color: "#2dd98a", name: "Mint"       },
  { color: "#14b8a6", name: "Teal"       },
  { color: "#06b6d4", name: "Cyan"       },
  { color: "#3b82f6", name: "Blue"       },
  { color: "#6366f1", name: "Indigo"     },
  { color: "#8b5cf6", name: "Violet"     },
  { color: "#a855f7", name: "Purple"     },
  { color: "#ec4899", name: "Pink"       },
  { color: "#f43f5e", name: "Rose"       },
  { color: "#64748b", name: "Slate"      },
  { color: "#6b7280", name: "Gray"       },
  { color: "#4a9eff", name: "Sky"        },
  { color: "#c084fc", name: "Lavender"   },
]
